### PR TITLE
fix: 214-today marker styling and overall page padding

### LINKED ISSUE #214: bug: today line text overlaps header labels on smaller screens
see https://github.com/pln-planning-tools/StarMaps/pull/211#pullrequestreview-1198790323 and:

image

### PR DESCRIPTION
**Pull request by djmcquillan**
fixes #214

- cleans up overall padding on container
- fixes overlap issue

### Demo Links
https://starmaps-gc1gl0vng-ipfs-ignite.vercel.app/

### CODE REVIEW

File: components/layout/PageHeader.tsx [hunk 1]
```diff
@@ -10,7 +10,7 @@ import { ErrorBoundary } from '../errors/ErrorBoundary';
 
 function PageHeader() {
   return (
-    <Flex direction={'row'} bg={theme.light.header.background.color} pl="120px" pr="120px">
+    <Flex direction={'row'} bg={theme.light.header.background.color} pr={{ base:"30px", sm:"30px", md:"60px", lg:"120px" }} pl={{ base:"30px", sm:"30px", md:"60px", lg:"120px" }}>
```
Comment (SgtPooki) [inline components/layout/PageHeader.tsx:13]: we should be able to use `rem` or `em` or `vh`/`vw`. Is there a reason we didn't?

**Review by SgtPooki — APPROVED** [review]

**Review by SgtPooki — APPROVED** [review]
